config/routes.rb
Coworking::Application.routes.draw do
  resources :places

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "static_pages/home"
  root to: "static_pages#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable#, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  devise :omniauthable

  def self.find_for_twitter_oauth(access_token, signed_in_resource=nil)
	data = access_token.extra.raw_info
	email = "#{data["id"]}@test.com"
	logger.info email
	if user = self.find_by_email(email)
	  user
	else # Create a user with a stub password. 
	  self.create!(email: email , password: Devise.friendly_token[0,20]) 
	end
  end
	def self.new_with_session(params, session)
	    super.tap do |user|
	      if data = session["devise.twitter_data"] && session["devise.twitter_data"]["extra"]["raw_info"]
	        user.email = data["email"]
	    end
	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :signed_in_user, only: [ :new, :edit, :create,
                                         :update, :destroy ]
  # GET /places
  # GET /places.json
  def index
    @current_place = ""
    if params[:search].present?
      @current_place = params[:search]
    else
      @current_place = "#{request.location.city} #{request.location.country unless request.location.country == 'Reserved'}"
    end
    @current_place = "Budapest, Hungary" if @current_place.blank?

    @places = Place.near(@current_place, 200, :order => :distance)
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    def signed_in_user
      if !user_signed_in?
        flash[:error] = "You must sign in to do it!"
        redirect_to new_user_session_path
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def twitter
	    # You need to implement the method below in your model
	    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

	    if @user.persisted?
	      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Twitter"
	      sign_in_and_redirect @user, :event => :authentication
	    else
	      session["devise.twitter_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Places", places_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path,
                method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Connect with Twitter", user_omniauth_authorize_path(:twitter) %></li>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coworking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |key,value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :address %>
  </div>
  <div class="field">
    <%= f.input :latitude %>
  </div>
  <div class="field">
    <%= f.input :longitude %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-large btn-primary' %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table class="table table-striped">
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.address %></td>
    <td><%= place.latitude %></td>
    <td><%= place.longitude %></td>
    <td><%= link_to 'Show', place, class: "btn btn-mini"  %></td>
    <td><%= link_to 'Edit', edit_place_path(place), class: "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', place, confirm: 'Are you sure?', method: :delete, class: "btn btn-mini btn-danger"  %></td>
  </tr>
<% end %>
</table>
<%= form_tag places_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil,
        :class => "btn btn-primary" %>
  </p>
<% end %>

<br />

<%= link_to 'New Place', new_place_path, class: "btn btn-primary"  %>
 <br><br><br><%= @current_place %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path, class: 'btn' %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @place.address %>
</p>

<p>
  <b>Latitude:</b>
  <%= @place.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @place.longitude %>
</p>

<h3>Nearby locations</h3>
<ul>
<% for place in @place.nearbys(10) %>
  <li><%= link_to place.address, place %> (<%= place.distance.round(2) %> miles)</li>
<% end %>
</ul>


<%= link_to 'Edit', edit_place_path(@place), class: 'btn' %> |
<%= link_to 'Back', places_path, class: 'btn' %>

app/views/static_pages/home.html.erb
<h1>Welcome at ITK-Coworking!</h1>
<p>You could find us on <%= link_to 'github', 'https://github.com/juhat/coworking/'  %> </p>